---
- hosts: default
  become: true
  tasks:
    - name: install useful tools
      package:
        name: "{{ item }}"
      with_items:
        - git
        - htop
        - vim

    - include: partition.yml
    - include: remote.yml
    - include: libvmi.yml
    - include: test_vm.yml
